Quotes Language:		germanguillemets
Base Header Level:	3
latex input:				basis-mmd-scrartcl
MyOptions:					font=droid, rules
latex input:				basis-mmd-style
Title:							Tischtennisregeln
MySubtitle:					OpenTT
Author:							Ekkart Kleinod
MyEmail:						schiri@ekkart.de
MyDate:							Stand: 27. August 2013
latex input:				basis-mmd-begin-doc

<!-- \maketitle -->

<!-- \tableofcontents -->
<!-- \cleardoublepage -->

<!-- \part{Tischtennisregeln A} -->

# Der Tisch

1.  Die Oberfläche des Tisches, die "Spielfläche", ist rechteckig, 2,74 m lang und 1,525 m breit.
	Sie ist 76 cm vom Boden entfernt und liegt völlig waagerecht auf.

2.  Die senkrechten Seiten der Oberfläche gehören nicht zur Spielfläche.

