Quotes Language:		germanguillemets
Base Header Level:	3
latex input:				basis-mmd-scrartcl
MyOptions:					font=droid, rules
latex input:				basis-mmd-style
Title:							Tischtennisregeln
MySubtitle:					OpenTT
Author:							Ekkart Kleinod
MyEmail:						schiri@ekkart.de
MyDate:							Stand: 27. August 2013
latex input:				basis-mmd-begin-doc

<!-- \maketitle -->

<!-- \tableofcontents -->
<!-- \cleardoublepage -->

<!-- \part{Tischtennisregeln A} -->
<h2>Tischtennisregeln A</h2>

# Der Tisch

1. Die Oberfläche des Tisches, die "Spielfläche", ist rechteckig, 2,74 m lang[^fussnote:2.74] und 1,525 m breit[^fussnote:1.525].
	Sie ist 76 cm vom Boden entfernt[^fussnote:76] und liegt völlig waagerecht auf.
2. Die senkrechten Seiten der Oberfläche gehören nicht zur Spielfläche.
3. Die Spielfläche kann aus jedem beliebigen Material bestehen.
	Ein den Bestimmungen entsprechender Ball, der aus einer Höhe von 30 cm darauf fallen gelassen wird, muss überall gleichmäßig etwa 23 cm hoch aufspringen.
4. Die Spielfläche muss gleichmäßig dunkelfarbig und matt sein, jedoch entlang der beiden 2,74 m langen Kanten eine 2 cm breite weiße "Seitenlinie" und entlang der beiden 1,525 m langen Kanten eine 2 cm breite weiße "Grundlinie" aufweisen.
5. Die Spielfläche wird durch ein senkrechtes, parallel zu den Grundlinien verlaufendes Netz in zwei gleichgroße "Spielfelder" geteilt und darf im gesamten Bereich eines Spielfeldes nicht unterbrochen sein.
6. Für Doppelspiele ist jedes Spielfeld durch eine 3 mm breite weiße "Mittellinie", die parallel zu den Seitenlinien verläuft, in zwei gleichgroße "Spielfeldhälften" geteilt; die Mittellinie gilt als Teil der beiden rechten Spielfeldhälften.


# Die Netzgarnitur

1. Die Netzgarnitur besteht aus dem Netz, seiner Aufhängung und den Pfosten einschließlich der Zwingen, mit denen sie am Tisch angebracht sind.
2. Das Netz ist auf einer Schnur aufgehängt, die an jedem Ende an einem senkrechten, 15,25 cm hohen Pfosten[^fussnote:15.25] befestigt ist. Die Außenseiten der Pfosten sind 15,25 cm von der Seitenlinie entfernt.
3. Der obere Rand des Netzes muss in seiner ganzen Länge einen Abstand von 15,25 cm zur Spielfläche haben.
4. Der untere Rand des Netzes muss sich in seiner ganzen Länge so dicht wie möglich an die Spielfläche anschließen, und die Seiten des Netzes müssen von oben bis unten an den Pfosten befestigt sein.


# Der Ball

1. Der Ball ist gleichmäßig rund.
	Sein Durchmesser beträgt 40 mm.
2. Das Gewicht des Balls beträgt 2,7 g.
3. Der Ball besteht aus Zelluloid oder ähnlichem Plastikmaterial und ist mattweiß oder mattorange.


# Der Schläger

1. Größe, Form und Gewicht des Schlägers sind beliebig.
	Das Blatt muss jedoch eben und unbiegsam sein.
2. Mindestens 85 % des Blattes, gemessen an seiner Dicke, müssen aus natürlichem Holz bestehen.
	Eine Klebstoffschicht innerhalb des Schlägerblattes darf durch Fasermaterial wie Karbonfiber, Glasfiber oder komprimiertes Papier verstärkt sein.
	Sie darf jedoch nicht mehr als 7,5 % der Gesamtdicke oder mehr als 0,35 mm ausmachen – je nachdem, was geringer ist.
3. Eine zum Schlagen des Balls benutzte Seite des Blattes muss entweder mit gewöhnlichem Noppengummi (Noppen nach außen, Gesamtdicke einschließlich Klebstoff höchstens 2,0 mm) oder mit Sandwich-Gummi (Noppen nach innen oder nach außen, Gesamtdicke einschließlich Klebstoff höchstens 4,0 mm) bedeckt sein.
	1. Gewöhnlicher Noppengummi ist eine einzelne Schicht aus nicht zellhaltigem (d.h. weder Schwamm- noch Schaum-) Gummi – natürlich oder synthetisch – mit Noppen, die gleichmäßig über seine Oberfläche verteilt sind, und zwar mindestens 10 und höchstens 30 pro Quadratzentimeter.
	2. Sandwich-Gummi ist eine einzelne Schicht aus Zellgummi (d.h. Schwamm- oder Schaumgummi), die mit einer einzelnen äußeren Schicht aus gewöhnlichem Noppengummi bedeckt ist.
		Dabei darf die Gesamtdicke des Noppengummis nicht mehr als 2 mm betragen.
4. Das Belagmaterial muss das Blatt völlig bedecken, darf jedoch nicht über die Ränder hinausstehen.
	Der dem Griff am nächsten liegende Teil des Blattes, der von den Fingern erfasst wird, darf unbedeckt oder mit einem beliebigen Material belegt sein.
5. Das Blatt selbst, jede Schicht innerhalb des Blattes und jede Belag- oder Klebstoffschicht auf einer zum Schlagen des Balles benutzten Seite müssen durchlaufend und von gleichmäßiger Dicke sein.
6. Beide Schlägerseiten – unabhängig davon, ob ein Belag vorhanden ist oder nicht – müssen matt sein, und zwar auf der einen Seite leuchtend rot, auf der anderen schwarz.
7. Das Belagmaterial muss ohne irgendeine physikalische, chemische oder sonstige Behandlung verwendet werden.
	1. Geringfügige Abweichungen von der Vollständigkeit des Belags oder der Gleichmäßigkeit seiner Farbe, die auf zufällige Beschädigung, auf Abnutzung oder Verblassen zurückzuführen sind, können zugelassen werden, sofern sie die Eigenschaften der Oberfläche nicht entscheidend verändern.
8. Vor Spielbeginn und jedes Mal, wenn er während des Spiels den Schläger wechselt, muss der Spieler seinem Gegner und dem Schiedsrichter den Schläger zeigen, mit dem er spielen will, und muss ihnen gestatten, den Schläger zu untersuchen.


# Definitionen

1. Ein Ballwechsel ist die Zeit, während der der Ball im Spiel ist.
2. Der Ball ist im Spiel vom letzten Moment an, in dem er – bevor er absichtlich zum Aufschlag hochgeworfen wird – auf dem Handteller der freien Hand ruht, bis der Ballwechsel als Let (Wiederholung) oder als Punkt entschieden wird.
3. Wird das Ergebnis eines Ballwechsels nicht gewertet, so bezeichnet man das als Let (Wiederholung).
4. Wird das Ergebnis eines Ballwechsels gewertet, so bezeichnet man das als Punkt.
5. Die Schlägerhand ist die Hand, die den Schläger hält.
6. Die freie Hand ist die Hand, die nicht den Schläger hält; der freie Arm ist der Arm der freien Hand.
7. Ein Spieler schlägt den Ball, wenn er ihn im Spiel mit dem in der Hand gehaltenen Schläger oder mit der Schlägerhand unterhalb des Handgelenks berührt.
8. Ein Spieler hält den Ball auf, falls er oder irgendetwas, das er an sich oder bei sich trägt, den Ball im Spiel berührt, wenn dieser sich über der Spielfläche befindet oder auf sie zufliegt und sein Spielfeld nicht berührt hat, seit er zuletzt von seinem Gegner geschlagen wurde.
9. Aufschläger ist der Spieler, der den Ball in einem Ballwechsel als Erster schlagen muss.
10. Rückschläger ist der Spieler, der den Ball in einem Ballwechsel als Zweiter schlagen muss.
11. Der Schiedsrichter ist die Person, die dafür eingesetzt wurde, das Spiel zu leiten.
12. Der Schiedsrichter-Assistent ist die Person, die dafür eingesetzt wurde, den Schiedsrichter mit bestimmten Entscheidungen zu unterstützen.
13. Etwas, das ein Spieler an sich oder bei sich trägt, schließt alles ein, was er zu Beginn des Ballwechsels an sich oder bei sich trug, mit Aus-
nahme des Balles.
14. Als über die Netzgarnitur oder um sie herum gilt auch, wenn der Ball das Netz irgendwo anders als zwischen Netz und Pfosten oder zwischen Netz und Spielfläche passiert.
15. Der Ausdruck Grundlinie schließt ihre gedachte Verlängerung in beide Richtungen ein.


# Der Aufschlag

1. Der Aufschlag beginnt damit, dass der Ball frei auf dem geöffneten Handteller der ruhig gehaltenen freien Hand des Aufschlägers liegt.
2. Der Aufschläger wirft dann den Ball, ohne ihm dabei einen Effet zu versetzen, nahezu senkrecht so hoch, dass er nach Verlassen des Handtellers der freien Hand mindestens 16 cm aufsteigt und dann herabfällt, ohne etwas zu berühren, bevor er geschlagen wird.
3. Wenn der Ball herabfällt, muss der Aufschläger ihn so schlagen, dass er zunächst sein eigenes Spielfeld berührt und dann über die Netzgarnitur oder um sie herum direkt in das Spielfeld des Rückschlägers springt oder es berührt.
	Im Doppel muss der Ball zuerst die rechte Spielfeldhälfte des Aufschlägers und dann die[^fussnote:sph] des Rückschlägers berühren.
4. Der Ball muss sich vom Beginn des Aufschlags bis er geschlagen wird oberhalb der Ebene der Spielfläche und hinter der Grundlinie des Aufschlägers befinden und darf durch den Aufschläger oder seinen Doppelpartner oder durch etwas, das sie an sich oder bei sich tragen, für den Rückschläger nicht verdeckt werden.
5. Sobald der Ball hochgeworfen wurde, müssen der freie Arm und die freie Hand des Aufschlägers aus dem Raum zwischen dem Ball und dem Netz entfernt werden.
	Anm.: Dieser Raum wird definiert durch den Ball, das Netz und dessen imaginäre, unbegrenzte Ausdehnung nach oben.
6. Es liegt in der Verantwortlichkeit des Spielers, so aufzuschlagen, dass der Schiedsrichter oder der Schiedsrichter-Assistent überzeugt sein kann, dass er die Bedingungen der Regeln erfüllt, und jeder der beiden kann entscheiden, dass ein Aufschlag unzulässig ist.
	1. Wenn entweder der SR oder der SR-Assistent über die Zulässigkeit eines Aufschlags nicht sicher ist, kann er, beim ersten Vorkommnis in einem Spiel, das Spiel unterbrechen und den Aufschläger verwarnen.
		Jeder folgende nicht eindeutig zulässige Aufschlag dieses Spielers oder seines Doppelpartners gilt jedoch als unzulässig.
7. In Ausnahmefällen kann der Schiedsrichter die Erfordernisse für einen korrekten Aufschlag lockern, wenn er überzeugt ist, dass ein Spieler sie wegen einer Körperbehinderung nicht einhalten kann.


# Der Rückschlag

1. Ein auf- oder zurückgeschlagener Ball muss so geschlagen werden, dass er über die Netzgarnitur oder um sie herum in das gegnerische Spielfeld springt oder es berührt, und zwar entweder direkt oder nach Berühren der Netzgarnitur.


[^fussnote:2.74]: 2,74 m entsprechen 9 Fuß (9 ft), mit 1 Fuß = 30,444... cm

[^fussnote:1.525]: 1,525 m entsprechen 5 Fuß (5 ft) mit 1 Fuß = 30,5 cm

[^fussnote:76]: 76 cm entsprechen 30 Zoll (30 inch) mit 1 Zoll = 2,5333... cm

[^fussnote:15.25]: 15,25 cm entsprechen 6 Zoll (6 inch) mit 1 Zoll = 2,541666... cm

[^fussnote:sph]: die rechte Spielhälfte des Rückschlägers

