Quotes Language:		germanguillemets
Base Header Level:	3
latex input:				basis-mmd-scrartcl
MyOptions:					font=droid, rules
latex input:				basis-mmd-style
Title:							Tischtennisregeln
MySubtitle:					OpenTT
Author:							Ekkart Kleinod
MyEmail:						schiri@ekkart.de
MyDate:							Stand: 27. August 2013
latex input:				basis-mmd-begin-doc

<!-- \maketitle -->

<!-- \tableofcontents -->
<!-- \cleardoublepage -->

<!-- \part{Tischtennisregeln A} -->
<h2>Tischtennisregeln A</h2>

# Der Tisch

1.  Die Oberfläche des Tisches, die "Spielfläche", ist rechteckig, 2,74 m lang[^fussnote:2.74] und 1,525 m breit[^fussnote:1.525].
	Sie ist 76 cm vom Boden entfernt[^fussnote:76] und liegt völlig waagerecht auf.
2.  Die senkrechten Seiten der Oberfläche gehören nicht zur Spielfläche.
3. Die Spielfläche kann aus jedem beliebigen Material bestehen.
	Ein den Bestimmungen entsprechender Ball, der aus einer Höhe von 30 cm darauf fallen gelassen wird, muss überall gleichmäßig etwa 23 cm hoch aufspringen.
4. Die Spielfläche muss gleichmäßig dunkelfarbig und matt sein, jedoch entlang der beiden 2,74 m langen Kanten eine 2 cm breite weiße "Seitenlinie" und entlang der beiden 1,525 m langen Kanten eine 2 cm breite weiße "Grundlinie" aufweisen.
5. Die Spielfläche wird durch ein senkrechtes, parallel zu den Grundlinien verlaufendes Netz in zwei gleichgroße "Spielfelder" geteilt und darf im gesamten Bereich eines Spielfeldes nicht unterbrochen sein.
6. Für Doppelspiele ist jedes Spielfeld durch eine 3 mm breite weiße "Mittellinie", die parallel zu den Seitenlinien verläuft, in zwei gleichgroße "Spielfeldhälften" geteilt; die Mittellinie gilt als Teil der beiden rechten Spielfeldhälften.




[^fussnote:2.74]: 2,74 m entsprechen 9 Fuß (9 ft), mit 1 Fuß = 30,444... cm

[^fussnote:1.525]: 1,525 m entsprechen 5 Fuß (5 ft) mit 1 Fuß = 30,5 cm

[^fussnote:76]: 76 cm entsprechen 30 Zoll (30 inch) mit 1 Zoll = 2,5333... cm

